services:
  mongodb:
    image: mongo:4.4
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_lora:/data/db
    networks:
      - LoRaWAN
  
  orion:
    image: fiware/orion:3.3.1
    hostname: orion
    depends_on:
      - mongodb
    ports:
      - "1026:1026"
      - "8888:8888"
    command: -dbhost mongodb -port 1026 -logLevel INFO 
    environment:
      - CB_HTTP_PORT=1026
      - CB_LOG_LEVEL=INFO
      - CB_PROMETHEUS_ENABLED=true
      - CB_PROMETHEUS_PORT=8888
    networks:
      - LoRaWAN

  iotagent-lora:
    depends_on:
      - orion
      - mongodb
    entrypoint: bin/iotagent-lora docker/config-docker.js
    hostname: iotagent-lora
    image: ioeari/iotagent-lora
    ports:
      - "4041:4041"
    networks:
      - LoRaWAN

  postgres-db:
    image: postgres:latest
    hostname: postgres-db
    container_name: db-postgres
    ports:
        - "5432:5432"
    networks:
        - LoRaWAN
    environment:
        - "POSTGRES_PASSWORD=password"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_DB=postgres"
    volumes:
        - postgres_data:/var/lib/postgresql/data
  
  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
        - LoRaWAN
    depends_on:
        - postgres-db
    ports:
        - "5055:5055"
        - "5080:5080"
    environment:
        - "CYGNUS_POSTGRESQL_HOST=postgres-db"
        - "CYGNUS_POSTGRESQL_PORT=5432"
        - "CYGNUS_POSTGRESQL_USER=postgres"
        - "CYGNUS_POSTGRESQL_PASS=password"
        - "CYGNUS_LOG_LEVEL=DEBUG"
    
  grafana:
    image: grafana/grafana
    depends_on:
        - postgres-db
    ports:
        - '3003:3000'
    environment:
        - GF_INSTALL_PLUGINS=orchestracities-map-panel,grafana-clock-panel,grafana-worldmap-panel
    networks:
      - LoRaWAN
    volumes:
      - grafana_data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - LoRaWAN


  simulador:
    build: ./Simular_sensores
    depends_on:
      - mosquitto
    networks:
      - LoRaWAN

  #SERVIÇOS DE MONITORAMENTO
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - LoRaWAN

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - LoRaWAN

  mosquitto-exporter:
    image: torilabs/mqtt-prometheus-exporter:latest
    hostname: mosquitto-exporter
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=tcp://mosquitto:1883
      - MQTT_USERNAME= # se tiver usuário
      - MQTT_PASSWORD= # se tiver senha
      - PROMETHEUS_PORT=9234
      - MQTT_CLIENT_ID=prometheus-exporter
    ports:
      - "9234:9234"   
    networks:
      - LoRaWAN


volumes:
  mongo_data_lora: 
  postgres_data:
  grafana_data: 

networks:
  LoRaWAN: {}